version: '3'
services:
  ryu:
    image: ryu:latest
    build:
      context: ryu
      dockerfile: Dockerfile
    privileged: true
    ports:
      - ${RYU_PORT:-8080}:8080
  floodlight:
    image: floodlight:latest
    build:
      context: floodlight
      dockerfile: Dockerfile
    privileged: true
    ports:
      - ${FLOODLIGHT_PORT:-8090}:8080
  mininet:
    image: mininet:latest
    build:
      context: mininet
      dockerfile: Dockerfile
    environment:
      - CONTROLLER=${CONTROLLER:-ryu}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flowvisor:
    image: flowvisor:latest
    build:
      context: flowvisor
      dockerfile: Dockerfile
    privileged: true
