version: '3'
services:
  mininet:
    image: mininet:latest
    build:
      context: mininet
      dockerfile: Dockerfile
    environment:
      - CONTROLLER=${CONTROLLER:-ryu}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ryu:
    image: ryu:latest
    build:
      context: ryu
      dockerfile: Dockerfile
    privileged: true
    ports:
      - ${RYU_PORT:-8080}:8080
  floodlight:
    image: floodlight:latest
    build:
      context: floodlight
      dockerfile: Dockerfile
    privileged: true
    ports:
      - ${FLOODLIGHT_PORT:-8090}:8080
  flowvisor:
    image: flowvisor:latest
    build:
      context: flowvisor
      dockerfile: Dockerfile
    privileged: true
  onstutorial:
    image: onstutorial:latest
    build:
      context: onstutorial
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DISPLAY=:0
    volumes:
      - ./display/socket:/tmp/.X11-unix
      - ./display/XAuthority:/root/.Xauthority
